# Generated by Django 5.1 on 2024-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry2',
            name='total_price',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
