# Generated by Django 5.1 on 2024-10-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userentry2_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='stock_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userentry2',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
