# Generated by Django 5.1 on 2024-11-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_stockitem2_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem2',
            options={},
        ),
        migrations.RenameField(
            model_name='stockitem2',
            old_name='stock_name',
            new_name='substock_name',
        ),
        migrations.RenameField(
            model_name='stockitem2main',
            old_name='stock_name',
            new_name='stock_main',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem2',
            unique_together=set(),
        ),
    ]
