# Generated by Django 5.1 on 2024-11-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_debt_stock_dimensions_alter_userentry2_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem2',
            old_name='discount_price',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='userentry2',
            old_name='discount_price',
            new_name='percentage',
        ),
    ]
