# Generated by Django 5.1 on 2024-11-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_stockitem2_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry2',
            old_name='item_name',
            new_name='substock_name',
        ),
    ]
